import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        fhd: "1920px",
        desktop: "1536px",
        laptop: "1200px",
        tablet: "768px",
      },
      colors: {
        mainBlue: "#3E65FE",
        mainViolet: "#D23CFF",
        label: "#433753",
        mainGray: "#ECEDF2",
        mainPink: "#ff7fce",
        mainOrange: "#fc956e",
        yellow: "#FEC83C",
      },
      keyframes: {
        fadeIn: {
          "0%": {
            opacity: "0.8",
            transform: "translateY(20px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
        },
        "text-1": {
          "0%, 10%": {
            left: "50%",
            top: "50%",
            opcacity: "0",
            zIndex: "7",
            background: "white",
            color: "#3E65FE",
            transform: "translateX(-50%) scale(0)",
          },
          "15%, 30%": {
            left: "50%",
            top: "40%",
            opcacity: "1",
            zIndex: "7",
            background: "#3E65FE",
            color: "white",
            transform: "translateX(-50%) scale(1.2)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "35%": {
            left: "50%",
            top: "40%",
            opcacity: "0",
            zIndex: "7",
            background: "#3E65FE",
            color: "white",
            transform: "translateX(-50%) scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "36%": {
            left: "auto",
            right: "-10%",
            top: "-5%",
            opcacity: "0",
            zIndex: "7",
            background: "#3E65FE",
            color: "white",
            transform: " scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "40%": {
            left: "auto",
            right: "-10%",
            top: "-5%",
            opcacity: "1",
            zIndex: "7",
            background: "#3E65FE",
            color: "white",
            transform: " scale(1)",
            boxShadow:
              "rgba(0, 0, 0, 0.07) 0px 1px 2px, rgba(0, 0, 0, 0.07) 0px 2px 4px, rgba(0, 0, 0, 0.07) 0px 4px 8px, rgba(0, 0, 0, 0.07) 0px 8px 16px, rgba(0, 0, 0, 0.07) 0px 16px 32px, rgba(0, 0, 0, 0.07) 0px 32px 64px;",
          },
        },
        "text-2": {
          "0%, 30%": {
            left: "50%",
            top: "50%",
            opcacity: "0",
            zIndex: "6",
            background: "white",
            color: "rgb(16 185 129)",
            transform: "translateX(-50%) scale(0)",
          },
          "35%, 45%": {
            left: "50%",
            top: "50%",
            opcacity: "1",
            zIndex: "6",
            background: "rgb(16 185 129)",
            color: "white",
            transform: "translateX(-50%) scale(1.2)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "50%": {
            left: "50%",
            top: "50%",
            opcacity: "0",
            zIndex: "6",
            background: "rgb(16 185 129)",
            color: "white",
            transform: "translateX(-50%) scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "53%": {
            left: "-10%",
            top: "30%",
            opcacity: "0",
            zIndex: "6",
            background: "rgb(16 185 129)",
            color: "white",
            transform: " scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "56%": {
            left: "-10%",
            top: "30%",
            opcacity: "1",
            zIndex: "6",
            background: "#10b981",
            color: "white",
            transform: " scale(1)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
        },
        "text-3": {
          "0%, 45%": {
            left: "50%",
            top: "50%",
            opcacity: "0",
            zIndex: "5",
            background: "white",
            color: "#D23CFF",
            transform: "translateX(-50%) scale(0)",
          },
          "50%, 55%": {
            left: "50%",
            top: "55%",
            opcacity: "1",
            zIndex: "5",
            background: "#D23CFF",
            color: "white",
            transform: "translateX(-50%) scale(1.2)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "60%": {
            left: "50%",
            top: "65%",
            opcacity: "0",
            zIndex: "5",
            background: "#D23CFF",
            color: "white",
            transform: "translateX(-50%) scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "63%": {
            left: "auto",
            right: "-4%",
            bottom: "20%",
            top: "auto",
            opcacity: "0",
            zIndex: "5",
            background: "#D23CFF",
            color: "white",
            transform: " scale(0)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
          "64%": {
            left: "auto",
            right: "-4%",
            bottom: "20%",
            top: "auto",
            opcacity: "1",
            zIndex: "5",
            background: "#D23CFF",
            color: "white",
            transform: " scale(1)",
            boxShadow: " rgba(17, 12, 46, 0.15) 0px 48px 100px 0px",
          },
        },

        "img-service-1": {
          "0%,22%, 100%": {
            filter: "grayscale(80%)",
            transform: "translateY(0px) scale(1)",
            zIndex: "1",
          },
          "5%, 18%": {
            filter: "grayscale(0%)",
            transform: "translateY(4px) scale(1.2)",
            zIndex: "2",
          },
        },
        "img-service-2": {
          "0%,18%,45%, 100%": {
            filter: "grayscale(80%)",
            transform: "translateY(0px) scale(1)",
            zIndex: "1",
          },
          "27%, 40%": {
            filter: "grayscale(0%)",
            transform: "translateY(4px) scale(1.2)",
            zIndex: "2",
          },
        },
        "img-service-3": {
          "0%,40%,65%, 100%": {
            filter: "grayscale(80%)",
            transform: "translateY(0px) scale(1)",
            zIndex: "1",
          },
          "45%, 60%": {
            filter: "grayscale(0%)",
            transform: "translateY(4px) scale(1.2)",
            zIndex: "2",
          },
        },
        zoomIn: {
          "0%": {
            opacity: "0",
            transform: "scale(0) translateY(-100%)",
          },
          "100%": {
            opacity: "1",
            transform: "scale(1) translateY(-50%)",
          },
        },
        zoomOut: {
          "0%": {
            opacity: "1",
            transform: "scale(1)",
          },
          "100%": {
            opacity: "0",
            transform: "scale(0)",
          },
        },
      },
      animation: {
        fadeIn: "fadeIn ease 1.2s",
        "text-1": "text-1 10s",
        "text-2": "text-2 10s",
        "text-3": "text-3 10s",
        "img-service-1": "img-service-1 20s infinite",
        "img-service-2": "img-service-2 20s infinite",
        "img-service-3": "img-service-3 20s infinite",
        zoomIn: "zoomIn ease 1s",
        zoomOut: "zoomOut ease 1s",
      },
      backgroundImage: {
        mainGradient: "linear-gradient(90.57deg, #3E65FE 0%, #D23CFF 100%)",
        "mainGradient-disabled":
          "linear-gradient(90deg, rgba(27,73,254,0.5) 15%, rgba(199,11,255,0.5) 100%)",
        secondaryGradient:
          "linear-gradient(90deg, rgba(255,127,206,1) 0%, rgba(252,149,110,1) 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
