import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ClientProvider from "@/@Provider/ClientProvider";
import Layout from "@/@Page/@Layout";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Educenter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ClientProvider>
          <Layout>{children}</Layout>
        </ClientProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
